ALTER TABLE riders
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE VARCHAR(64) USING created_at::TEXT,
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE VARCHAR(64) USING updated_at::TEXT,
  ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE stations
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE VARCHAR(64) USING created_at::TEXT,
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE VARCHAR(64) USING updated_at::TEXT,
  ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE transactions
  ALTER COLUMN payment_date TYPE VARCHAR(64) USING payment_date::TEXT,
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE VARCHAR(64) USING created_at::TEXT,
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE VARCHAR(64) USING updated_at::TEXT,
  ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE auth_accounts
  ALTER COLUMN created_at DROP DEFAULT,
  ALTER COLUMN created_at TYPE VARCHAR(64) USING created_at::TEXT,
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN updated_at DROP DEFAULT,
  ALTER COLUMN updated_at TYPE VARCHAR(64) USING updated_at::TEXT,
  ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
